[package]
name = "hotstuff_rs"
version = "0.0.0"
description = "An implementation of the HotStuff consensus algorithm."
homepage = "https://parallelchain.io"
repository = "https://github.com/parallelchain-io/hotstuff_rs"
readme = "README.md"
edition = "2021"
license = "GPL-2.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocksdb = "0.19.0"
threadpool = "1.8.1"
