[package]
name = "hotstuff_rs_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.9"
ed25519-dalek = "1"
sha2 = "0.10"